In [6]:
import matplotlib.pyplot as plt 

import scipy.ndimage.filters

import skimage.color

from PIL import Image
from PIL import ImageFilter

import numpy as np

from skimage import io, color, feature,filters,morphology, draw

import math


In [25]:
def detectCircles(im, radius, usegradient):
    edge = np.where(im == True)
    H = np.zeros(im.shape)
    for e in range(len(edge[0])):
        y, x = skimage.draw.circle_perimeter( edge[1][e], edge[0][e], radius)
        np.where( np.array([x,y]) )
        H[x, y] +=1
    return H
           
# Preprocessing
image = np.asarray(Image.open("Images/Q2/ladybug.jpg"),dtype=np.float64)/255.0
# convert to greyscale
image=skimage.color.rgb2grey(image)

# Edge detect
canny_map=feature.canny(image, low_threshold = 0.025, high_threshold= .15)
# r, t, H = hough_transform(canny_map)

# guassain blur to reduce noise

# get circles
circles = detectCircles(canny_map,1 , 3)

# draw circles on origional image 

%matplotlib inline
plt.figure()
plt.imshow(circles)

print(np.max(circles))


[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [54]:
canny_map[1][1]


array([False, False, False, ..., False, False, False], dtype=bool)